### ISSUE TITLE
your website is down

### ISSUE THREAD

**Issue by bernd972** [fferrin/free-medium#11]
Well, the read.medium.com website seems to be down, so the extension doesnt work either.

**Comment by bandaot** [comment]
@bernd972 It works for me now.

**Comment by fferrin** [comment]
Hi @bernd972 . The (external) website is not read.medium.com but https://readmedium.com/. If the extension is not working (meaning, readmedium.com is down), you can always try the previous website used by the extension (https://freedium.cfd/) by checking out to a previous commit (ebc45a2871dd64eb0372aba99d2442074755af51, for example, and try that as well.

As @bandaot said, it's working for me too, so I'm closing this issue but feel free to reopen it if you find any other problem.
