### ISSUE TITLE
It Doesnt work on this kind of link

### ISSUE THREAD

**Issue by champolot** [fferrin/free-medium#17]
https://uxmovement.medium.com/how-to-handle-a-massive-filter-with-over-100-options-dc8b1966d3c7

**Comment by fferrin** [comment]
Hi @champolot . I just tried the link and it works for me. Make sure you pulled the latest changes (commit hash [8e14d3b48c601a3ecd4e56d71fea11275b21d09e](https://github.com/fferrin/free-medium/commit/8e14d3b48c601a3ecd4e56d71fea11275b21d09e)).

Let me know if you still have problems.

![image](https://github.com/user-attachments/assets/897ece22-392d-406d-9fcd-5e1a9e214f85)
