### ISSUE TITLE
need detailed readme to insall the extension

### ISSUE THREAD

**Issue by somesh-bagadiya** [fferrin/free-medium#4]
Hello, 

I am unable to install the extension. When selecting the extension folder, it is getting installed but for some reason it is not working. I think I am doing something wrong. Please help!

**Comment by fferrin** [comment]
Hi @somesh-bagadiya , happy to help you with this. Were you able to import the extension in your browser? If so, can you confirm that you see it on the top right section of your browser? Or you can check that going to this site in your URL: `chrome://extensions/`

![image](https://github.com/fferrin/free-medium/assets/7387552/856e2bff-3557-4f17-9d1d-fcf0b86ef3ae)

**Comment by somesh-bagadiya** [comment]
yeah I can see the extensions, do you want me to disable the adblock?

**Comment by fferrin** [comment]
No need to disable the Adblock. Can you share with me what OS are you using (MacOS, Linux, Windows) and which browser? Just to double check, you should see this blue bottom at the bottom right corner of your browser (example link [here](https://medium.com/the-research-nest/optimizing-memory-usage-in-python-e8a30e0dddd3))

![image](https://github.com/fferrin/free-medium/assets/7387552/6f1c09c5-113a-4412-859e-94b3679d1277)

**Comment by shinolex** [comment]
Same for me, when I try to load it as unpacked it says "Manifest file is missing or unreadable" I gave the root directory when I try to load it

**Comment by fferrin** [comment]
Hi @shinolex. Glad you were able to solve it. Yes, you have to use the `extensions` folder when importing this in your browser. I separated this to import only the necessary files (and to make it easy to upload to extension ZIP file to the Google Chrome Store, but I guess I don't need it anymore since they don't accept it)

**Comment by fferrin** [comment]
I'm closing this. Let me know if you still need some help with the installation process
